name: coffee_shope
description: Coffee_shope Application.


publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  smooth_page_indicator: ^1.0.0+2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true

  assets:
  - assets/images/catalog-patel-image.png
  - assets/images/catalog-bebida-image.png
  - assets/images/coffee_image.png
  - assets/images/coffe-milk-image.png
  - assets/images/cocoa-caramel-image.png
  - assets/images/nitro-cold-brew-image.png
  - assets/images/caffe-macha-image.png
  - assets/icons/filter-icon.png
  - assets/icons/rating-icon.png
  - assets/icons/price-icon.png
  - assets/icons/promotion-icon.png
  - assets/icons/cocacola-icon.png
  - assets/icons/fanta-laranja-icon.png
  - assets/icons/fanta-uva-icon.png
  - assets/icons/guarana-icon-.png
  - assets/icons/pastel-icon-png.jpeg

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
